language: java
jdk:
- oraclejdk8
- openjdk8
cache:
  directories:
  - "$HOME/.gradle"
after_success:
- |
  test "${TRAVIS_PULL_REQUEST}" = 'false' && "./gradlew bintrayUpload"
notifications:
  webhooks:
    urls:
    - secure: feEKRGM5pwxP6FenUYuGRNgxXj4O5vQfSsm8x3Zmv//pau4CEnKJ10R58Knu4aHdNuRab5U9OZF7vtcdCOtxdUUWULmCj5XFgUOdcyXpgkdMN9zkcV54bTU2DdwRqXX19h1Uas+bTxVvJLQy+OWX9BaGXvCcHKXvhh5OmcRoLmoHcpizrnMkahAh7uaOuhqgSVV/vSRv/RLYACrIbyT40b/CXeHenraJhLZMXBYtgTkgXQaxIjXHEZp3bcuYM2ErQCoRxvT32RO+qBtWthAWhpzFATBLKIYUoyJmPUvfFuD5iGOdPEvSm7Xkwh2efLFNsRqwMJwPFg5+tCjFo/Ln2zgZ4PwNHA9BE9H4W7RderqSQlMz6N/uQDeXJJiFWB1IWZUVMuPBuM89sfALvPmlxD4jUbokJwgJBkGiX7CdNM7kZKzMytqAGBtemgwWGBSd3AY9YA/8mTR7mY18hWxAjfrAB8v7U9/BjvZycgXGO6kmAGn3gWJF7JTxwl/Awr/TrOPt/1zT0jyAc8x5YWLoiUhiA/PHcM4TmNm877jsCRROxUJgGvHlOFYKjKAYSay6Uj7CBS2OLaepclReRRXKokgdi6SZrwbBkwSAwzZ7aRoecZ0IZ2LGa0752dlHIK/ZaFd0eWlFYWBbL8n2GawlI7qp4bBzfs5T0gaSWgO8mYQ=
  "    on_success": change
  "    on_failure": always
  "    on_start": false
env:
  global:
  - secure: h2WJrcBVf4AwqeJt1HpErFN5pnPEeiiGawuodqM1gJLcrKx5faeMsqShx+WV19edI1Ht7umDH/8eJx5YdF8C5FJ8wCcxblfXjgD6xUABB8tgheYqwIIcJhYRa8TlLqc28R+IRLeoWLI5qu/R4KPBSHemlDqlqmEiIwMfRDGCVM8PU1XiL8YxSMH6zJuclZ6dtUkRZ7ZivoEV8k1zH7JfhRnwQGqHvgFnEGU0UTyVBgbv/dv8wuK1TihRWZxJlJV+vQoCIVg5W+fKV9a79i6xMhk6JR6Saylg8ScJfqIeAfaPx41STrBYXEcnV3joXQRFrHBl/p1J5O9cQlIX6TLDRZ9FauDV2cLqnhOvME5M5lH6F3bfhjncjnYYSRMu78Z72L99SMjHcw2fPT7QAeTFR2UwnaagoyaXumE1Y+3iMNee5YQZ+3QDzDgZFCb6pd30I98p09P9NbzgIHzvr6NS5EUIF2Lh+RrLstblSksKFNTNlohjFtZ14WJ+CwsjwXSRwq6RTJN3HV+ax0fai4BEDw7mkB0KGlws0gEC9+oBltIidy5wrzsy4di2q9lbqDRSObYvvqqwCuq1b09quwAW1GXylczyu9XBUYUqoxpHjRTej+hFWdVSi7XfQxYwf59XMdttUKHUJiPPJGAjmJFL67qM73B77UkIVFyseUPXi3Q=
  - secure: Es8NC27sQAKc39NMzicMpcsxMbZZxT7Kn+qPQjtNGgMySt+AF9rPzTCLkPdjMjQCFBwXBhW8WT1b9hZxChp6FSWxb1/+0JMe8wa8cWikPUWU+Xy/Ww7+hMktgBddrP6mUxPQioifjJMCnQFJ240ZOJIx8fY7i9eyxlo86OUQ6DrY6C9043HsepNaDloNvkrCRT5BNN6B45Z/w/kT2euk9Dv/+1kis8lsRyiqGjNI3MqjPpnd8RHWoPLlPcjBj257MBU9ujIU2V2oQg9lHYUxkCcd4YNaS6HPQWseZ0qhNrulh8d5YdMcmHGJXPf5MCy4qWM8HQaNWGBdU9+e5Q1m+2tY1LGe6/Zt0KNfYIRh5qSX9zazyRMnmLt5yG2gaYgIQ7T/CBelwDPTTKWaa4m5FWE6sHE64wa5WR1iGkNhCdgtYOMDBcyxR/6oyrbdKG/qDb8DnkLozsNV+NsGAXZTa79NnZ18Zr0OtypguyG0cbkCdF53EpAxGnpVVhAJYvKzynuHT0zQwMyitozg+Y6AwgfvA9HPDzlmPmni+Q7Jvlz0JTHHak+cxjF4goCIIzyVJFLOhweErV7RbJND5sPBQyTn+4bgCKWWYyMHLoQ2jagdi6zO0qNhQjj6KQPsa/bwIpB9AU89Q7FtITo+Oncx8kQj+Ox9q9lsUoBTnJI+7+o=
